### ISSUE TITLE
docker如何配置正式部署?

### ISSUE THREAD

**Issue by onekyle** [rock-app/fabu.love#115]
按照readme中使用docker部署,本地运行一切正常
我想要切换到正式模式,于是编辑 `docker/docker-compose.yml`
```
server:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      FABU_DB_HOST: mongo
      FABU_BASE_URL: https://www.***.app/dis
      FABU_UPLOAD_DIR: /fabu/upload
      NODE_ENV: production
```
然后移除了已存在的docker image 重新执行`docker-compose up -d --build`
执行完毕后 发现还是只能通过`http://www.**.app:9898`进行访问.

感谢开发团队开源.
